# Generated by Django 3.0.8 on 2020-07-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programName', models.CharField(max_length=100)),
                ('collegeName', models.CharField(max_length=100)),
                ('districName', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('refernceLink', models.CharField(max_length=200)),
            ],
        ),
    ]
